apiVersion: v1
kind: Service
metadata:
  name: tf-service
  labels:
    app: tf
spec:
  type: NodePort
  ports:
  - name: tf
    port: 8888
  - name: tf-web
    port: 80
    targetPort: 6006
  selector:
    app: tf
